# Generated by Django 5.1.3 on 2024-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
