# Generated by Django 5.1.3 on 2024-11-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='category',
            new_name='Add_Tag',
        ),
    ]
