# Generated by Django 5.1.3 on 2024-11-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweet.tweet'),
        ),
    ]
