# Generated by Django 5.1.3 on 2024-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_comment_postof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='about_blog',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
