# Generated by Django 5.1.3 on 2024-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_alter_tweet_about_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='Add_Tag',
            new_name='add_tag',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='about_blog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
