# Generated by Django 5.1.3 on 2024-11-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_rename_add_tag_tweet_add_tag_alter_tweet_about_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='add_tag',
            field=models.CharField(choices=[('personal', 'Personal'), ('news', 'News'), ('food', 'Food'), ('product', 'Product'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
