# Generated by Django 5.1.3 on 2024-11-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_alter_tweet_add_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='add_tag',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('food', 'Food'), ('product', 'Product'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
